services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mxcoan\Service\ConnectService: ~
    Mxcoan\Subscriber\SystemConfigChangedSubscriber: ~
    Mxcoan\Controller\ChallengeController:
        public: true